### ISSUE TITLE
点击搜索再取消会产生block引用循环问题

### ISSUE THREAD

**Issue by Wuou** [lilongcnc/LLSearchViewController#1]
- (void)creatSearchNaviBar 方法里

 __weak __typeof(self) weakSelf = self;
    
#warning block 内存泄漏
//    @LLWeakObj(self);
    [searchNaviBarView setSearchBarBeignOnClickBlock:^{
       
//        @LLStrongObj(self);
        
        HistorySearchVC *searShopVC = [HistorySearchVC new];  // retian + 1
        
      
        //(1)点击分类 (2)用户点击键盘"搜索"按钮  (3)点击历史搜索记录
        [searShopVC beginSearch:^(NaviBarSearchType searchType,NBSSearchShopCategoryViewCellP *categorytagP,UILabel *historyTagLabel,LLSearchBar *searchBar) {
            
            
            NSLog(@"historyTagLabel:%@--->searchBar:%@--->categotyTitle:%@--->%@",historyTagLabel.text,searchBar.text,categorytagP.categotyTitle,categorytagP.categotyID);
            
            searShopVC.searchBarText = @"你选择的搜索内容显示到这里";
        }];
        //执行即时搜索匹配
        NSArray *tempArray =  @[@"Java", @"Python"];
        [searShopVC searchbarDidChange:^(NaviBarSearchType searchType, LLSearchBar *searchBar, NSString *searchText) {
            //FIXME:这里模拟网络请求数据!!!
            dispatch_after(dispatch_time(DISPATCH_TIME_NOW, (int64_t)(0.1f * NSEC_PER_SEC)), dispatch_get_main_queue(), ^{
                searShopVC.resultListArray = tempArray;
            });
        }];
        
        [weakSelf.navigationController presentViewController:searShopVC animated:NO completion:nil];

**Comment by lilongcnc** [comment]
非常感谢你提出这个问题，之前太粗心了，LLWeakObj和LLStrongObj这两个没有在block中写全面，导致了这个问题！ 现在已经修复
